version: "2"

linters:
  enable:
    - asciicheck
    - depguard
    - dupword
    - durationcheck
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nolintlint
    - predeclared
    - revive
    - testifylint
    - unconvert

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: io/ioutil
              desc: Use corresponding 'os' or 'io' functions instead.
            - pkg: github.com/pkg/errors
              desc: Use 'errors' or 'fmt' instead of github.com/pkg/errors
            - pkg: golang.org/x/exp/slices
              desc: Use 'slices' instead.
    gosec:
      excludes:
        - G107
    revive:
      rules:
        - name: var-naming
          disabled: true
        - name: empty-block
          disabled: true

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - govet
        text: structtag
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
