linters:
  enable:
    - asciicheck
    - depguard
    - dupword
    - durationcheck
    - errorlint
    - gosec
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - misspell
    - nolintlint
    - predeclared
    - revive
    - testifylint
    - unconvert

linters-settings:
  gofmt:
    simplify: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: "Use corresponding 'os' or 'io' functions instead."
          - pkg: "github.com/pkg/errors"
            desc: "Use 'errors' or 'fmt' instead of github.com/pkg/errors"
          - pkg: "golang.org/x/exp/slices"
            desc: "Use 'slices' instead."
  revive:
    # https://github.com/mgechev/revive/blob/master/defaults.toml
    # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
    rules:
      - name: var-naming
        disabled: true
      - name: empty-block
        disabled: true
  gosec:
    # Available rules: https://github.com/securego/gosec#available-rules
    excludes:
      - G107 # This project aren't calling unknown URL

issues:
  exclude-rules:
    - text: 'structtag'
      linters:
        - govet
