name: files-changed

on:
  workflow_call:
    outputs:
      lib:
        value: ${{ jobs.detect.outputs.lib }}
      actions:
        value: ${{ jobs.detect.outputs.actions }}
      docs:
        value: ${{ jobs.detect.outputs.docs }}

jobs:
  detect:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      lib: ${{ steps.changes.outputs.lib }}
      actions: ${{ steps.changes.outputs.actions }}
      docs: ${{ steps.changes.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |

            lib:
              - "code/**/*.go"
              - "go.mod"
              - "go.sum"
              - ".golangci.yml"

            actions:
              - added|modified:
                - ".github/workflows/*"

            docs:
              - "**/*.md"
